kw = ['Comercio', 'Exterior', 'Diseño', 'Organizacional', 'Economía', 'Empresa', 'Entorno', 'Organizacional', 'Estrategia',
      'Planeación', 'Fundamentos', 'Mercadeo', 'Fundamentos', 'Responsabilidad', 'Social', 'Empresarial', 'Gerencia', 'Ventas',
      'Gestión', 'Producción', 'Bienes', 'Servicios', 'Gestión', 'Sistemas', 'Info.', 'Gestión', 'Financiera',
      'Presupuestos', 'Investigación', 'Mercados', 'Investigación', 'Operaciones', 'Microeconomía', 'Política', 'Econ.', 
      'Nacional', 'Internacional', 'Procesos', 'Fabricación', 'Bienes', 'Servicios', 'Publicidad', 'Sociología', 'Organizaciones',
      'Herramientas', 'informáticas', 'gestión', 'Fundamentos', 'contabilidad', 'Legislación', 'Laboral', 'Evaluación', 
      'Administración', 'Proyectos', 'Fundamentos', 'Economía', 'Comercio', 'Inglés', 'Construcción', 'Edificaciones', 
      'Estructuras', 'Física', 'construcción', 'Materiales', 'Construcción', 'Taller', 'Representación', 'Derecho', 
      'Constitución', 'política', 'Análisis', 'Costos', 'Presupuestos', 'Casos', 'contables', 'especiales', 'Casos', 
      'Contables', 'Especiales', 'Contabilidad', 'recursos', 'obligaciones', 'corto', 'plazo', 'Control', 'auditoría', 
      'Dirección', 'organización', 'contable', 'Electiva', 'Profesional', 'Procedimiento', 'Tributario', 'Electiva', 
      'Profesional', 'IV:', 'Fundamentos', 'Contabilidad', 'Internacional', 'Fundamentos', 'Costos', 'Legislación', 'comercial', 
      'Legislación', 'tributaria', 'Legislación', 'Tributaria', 'Procesos', 'costos', 'Revisoría', 'Fiscal', 'Seminario', 
      'Teoría', 'Contable', 'Sistemas', 'Producción', 'Software', 'procesos', 'contables', 'Legislación', 'Comercial', 
      'Macroeconomía', 'coyuntura', 'Proceso', 'administrativo', 'Cálculo', 'monovariable', 'Estadística', 'Aseguramiento', 
      'calidad', 'Industria', 'Alimentos', 'Control', 'instrumentación', 'Industria', 'Alimentos', 'Deshidratación', 'alimentos', 
      'Física', 'Informática', 'Mecánica', 'Fluidos', 'Procesos', 'fermentación', 'alimentos', 'Talleres', 'laboratorios', 
      'Ingeniería', 'Alimentos', 'Termodinámica', 'General', 'Transferencia', 'masa', 'proceso', 'Alimentos', 'Análisis', 
      'Económico', 'Inversiones', 'Programación', 'aplicaciones', 'web', 'Arquitectura', 'Computadores', 'Cálculo', 
      'Multivariable', 'Ciberseguridad', 'Complejidad', 'Optimización', 'Modelación', '3D', 'Programación', 'aplicaciones', 
      'móviles', 'Minería', 'datos', 'Ecuaciones', 'Diferenciales', 'Fundamentos', 'Lenguajes', 'Programación', 'Fundamentos', 
      'Redes', 'Inteligencia', 'Artificial', 'Simulación', 'Computacional', 'Análisis', 'Métodos', 'Numéricos', 'Física', 
      'Álgebra', 'Lineal', 'Bases', 'Datos', 'Análisis', 'Diseño', 'Algoritmos', 'Matemáticas', 'Básicas', 'Matemáticas', 
      'Discretas', 'Sistemas', 'Operativos', 'Fundamentos', 'Programación', 'Español', 'Control', 'Electrónico', 'Potencia', 
      'Microprocesadores', 'Sistemas', 'automáticos', 'control', 'Sistemas', 'Comunicación', 'Química', 'Biología']

carreras = ['Administración de empresas', 'Contaduría', 'Construcción', 'Ingeniería de Sistemas', 'Ingeniería de Alimentos',
            'Trabajo social', 'Tecnología en Desarrollo de Software', 'Nutrición y Dietética', 'Tecnología en Electrónica']
metodos = ["Aprendizaje Activo","Aprendizaje Reflexivo","Aprendizaje Teórico","Aprendizaje Pragmático","Aprendizaje Visual",
           "Aprendizaje Auditivo","Aprendizaje Kinestésico"]
materias = [
    "Comercio Exterior", "Diseño Organizacional", "Economía de Empresa", "Entorno Organizacional",
    "Estrategia y Planeación", "Fundamentos de Mercadeo", "Fundamentos de Responsabilidad Social Empresarial",
    "Gerencia de Ventas", "Gestión de la Producción de Bienes y Servicios", "Gestión de los Sistemas de Info. Y las Tel.",
    "Gestión Financiera y Presupuestos", "Investigación de Mercados", "Investigación de Operaciones", "Microeconomía",
    "Política Econ. Nacional e Internacional", "Procesos de Fabricación de Bienes y Servicios", "Publicidad",
    "Sociología de las Organizaciones", "Herramientas informáticas para la gestión", "Fundamentos de contabilidad",
    "Legislación Laboral", "Evaluación y Administración de Proyectos", "Fundamentos de Economía y Comercio", "Inglés",
    "Construcción de Edificaciones", "Estructuras", "Física de la construcción", "Materiales de Construcción",
    "Taller de Representación", "Derecho y Constitución política", "Análisis de Costos y Presupuestos",
    "Casos contables especiales II", "Casos Contables Especiales I", "Contabilidad de los recursos y obligaciones de corto plazo",
    "Control y auditoría", "Dirección y organización contable", "Electiva Profesional III: Procedimiento Tributario",
    "Electiva Profesional IV: Fundamentos de Contabilidad Internacional", "Fundamentos de Costos", "Legislación comercial II",
    "Legislación tributaria II", "Legislación Tributaria I", "Procesos de costos II", "Revisoría Fiscal",
    "Seminario de Teoría Contable", "Sistemas de Producción", "Software y procesos contables",
    "Legislación Comercial I", "Macroeconomía y coyuntura", "Proceso administrativo", "Cálculo monovariable",
    "Estadística", "Aseguramiento de la calidad en la Industria de Alimentos", "Control e instrumentación en la Industria Alimentos",
    "Deshidratación de alimentos", "Física III", "Informática I", "Mecánica de Fluidos",
    "Procesos de fermentación de alimentos", "Talleres y laboratorios Ingeniería Alimentos IV", "Termodinámica General",
    "Transferencia de masa en el proceso de Alimentos", "Análisis Económico de Inversiones", "Programación de aplicaciones web",
    "Arquitectura de Computadores", "Cálculo Multivariable", "Ciberseguridad", "Complejidad y Optimización",
    "Modelación 3D", "Programación de aplicaciones móviles", "Minería de datos", "Ecuaciones Diferenciales",
    "Fundamentos de Lenguajes de Programación", "Fundamentos de Redes", "Inteligencia Artificial", "Simulación Computacional",
    "Análisis y Métodos Numéricos", "Física I & II", "Álgebra Lineal", "Bases de Datos", "Análisis y Diseño de Algoritmos",
    "Matemáticas Básicas", "Matemáticas Discretas", "Sistemas Operativos", "Fundamentos de Programación", "Español",
    "Control Electrónico de Potencia", "Microprocesadores", "Sistemas automáticos de control", "Sistemas de Comunicación",
    "Química", "Biología"
]